# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtastic/protobuf/destinations.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'meshtastic/protobuf/destinations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from meshtastic.protobuf import lora_config_pb2 as meshtastic_dot_protobuf_dot_lora__config__pb2
from meshtastic.protobuf import nanopb_pb2 as meshtastic_dot_protobuf_dot_nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&meshtastic/protobuf/destinations.proto\x12\x13meshtastic.protobuf\x1a%meshtastic/protobuf/lora_config.proto\x1a meshtastic/protobuf/nanopb.proto\"\x93\x05\n\x12\x44\x65stinationsConfig\x12\x14\n\x0c\x64\x65\x66\x61ult_dest\x18\x01 \x01(\r\x12\x15\n\rnodeinfo_dest\x18\x02 \x01(\r\x12\x16\n\x0etelemetry_dest\x18\x03 \x01(\r\x12\x15\n\rposition_dest\x18\x04 \x01(\r\x12T\n\x0c\x64\x65stinations\x18\x05 \x03(\x0b\x32\x37.meshtastic.protobuf.DestinationsConfig.MeshDestinationB\x05\x92?\x02\x10\x08\x12\x15\n\rleaps_enabled\x18\x06 \x01(\x08\x12\x1b\n\x0cleap_channel\x18\x07 \x01(\rB\x05\x92?\x02\x38\x08\x12\x1b\n\x13lora_switch_enabled\x18\x08 \x01(\x08\x12 \n\x18only_lora_switch_from_us\x18\t \x01(\x08\x12!\n\x19only_leap_switch_messages\x18\n \x01(\x08\x12\x1f\n\x10nodeinfo_channel\x18\x0b \x01(\rB\x05\x92?\x02\x38\x08\x1a\x93\x02\n\x0fMeshDestination\x12\x0b\n\x03num\x18\x01 \x01(\r\x12\x1d\n\thop_limit\x18\x02 \x01(\rB\x05\x92?\x02\x38\x08H\x00\x88\x01\x01\x12\x1c\n\x08next_hop\x18\x03 \x01(\rB\x05\x92?\x02\x38\x08H\x01\x88\x01\x01\x12\x17\n\nfirst_leap\x18\x04 \x01(\rH\x02\x88\x01\x01\x12\x16\n\tlast_leap\x18\x05 \x01(\rH\x03\x88\x01\x01\x12=\n\x0blora_switch\x18\x06 \x01(\x0b\x32#.meshtastic.protobuf.LoRaConfigLiteH\x04\x88\x01\x01\x42\x0c\n\n_hop_limitB\x0b\n\t_next_hopB\r\n\x0b_first_leapB\x0c\n\n_last_leapB\x0e\n\x0c_lora_switchBg\n\x13\x63om.geeksville.meshB\x12\x44\x65stinationsProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtastic.protobuf.destinations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.geeksville.meshB\022DestinationsProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_DESTINATIONSCONFIG_MESHDESTINATION'].fields_by_name['hop_limit']._loaded_options = None
  _globals['_DESTINATIONSCONFIG_MESHDESTINATION'].fields_by_name['hop_limit']._serialized_options = b'\222?\0028\010'
  _globals['_DESTINATIONSCONFIG_MESHDESTINATION'].fields_by_name['next_hop']._loaded_options = None
  _globals['_DESTINATIONSCONFIG_MESHDESTINATION'].fields_by_name['next_hop']._serialized_options = b'\222?\0028\010'
  _globals['_DESTINATIONSCONFIG'].fields_by_name['destinations']._loaded_options = None
  _globals['_DESTINATIONSCONFIG'].fields_by_name['destinations']._serialized_options = b'\222?\002\020\010'
  _globals['_DESTINATIONSCONFIG'].fields_by_name['leap_channel']._loaded_options = None
  _globals['_DESTINATIONSCONFIG'].fields_by_name['leap_channel']._serialized_options = b'\222?\0028\010'
  _globals['_DESTINATIONSCONFIG'].fields_by_name['nodeinfo_channel']._loaded_options = None
  _globals['_DESTINATIONSCONFIG'].fields_by_name['nodeinfo_channel']._serialized_options = b'\222?\0028\010'
  _globals['_DESTINATIONSCONFIG']._serialized_start=137
  _globals['_DESTINATIONSCONFIG']._serialized_end=796
  _globals['_DESTINATIONSCONFIG_MESHDESTINATION']._serialized_start=521
  _globals['_DESTINATIONSCONFIG_MESHDESTINATION']._serialized_end=796
# @@protoc_insertion_point(module_scope)
