"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import meshtastic.protobuf.lora_config_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DestinationsConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MeshDestination(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NUM_FIELD_NUMBER: builtins.int
        HOP_LIMIT_FIELD_NUMBER: builtins.int
        NEXT_HOP_FIELD_NUMBER: builtins.int
        FIRST_LEAP_FIELD_NUMBER: builtins.int
        LAST_LEAP_FIELD_NUMBER: builtins.int
        LORA_SWITCH_FIELD_NUMBER: builtins.int
        num: builtins.int
        """
        The node number for this destination
        """
        hop_limit: builtins.int
        """
        Alternative hop limit to use for this destination (zero represents default)
        """
        next_hop: builtins.int
        """
        Manual next hop specification for messages to this node (zero represents default)
        """
        first_leap: builtins.int
        """
        Node number of first desired leap node toward this destination (optional).
        At least one of first_leap or last_leap should be set to a valid node number
        if leaping is desired.
        """
        last_leap: builtins.int
        """
        Node number of last desired leap node toward this destination (optional).
        This should ordinarily be the closest reliable node to the destination.
        """
        @property
        def lora_switch(self) -> meshtastic.protobuf.lora_config_pb2.LoRaConfigLite:
            """
            LoRa modem settings to switch out temporarily for messages sent to this destination.
            """

        def __init__(
            self,
            *,
            num: builtins.int = ...,
            hop_limit: builtins.int | None = ...,
            next_hop: builtins.int | None = ...,
            first_leap: builtins.int | None = ...,
            last_leap: builtins.int | None = ...,
            lora_switch: meshtastic.protobuf.lora_config_pb2.LoRaConfigLite | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_first_leap", b"_first_leap", "_hop_limit", b"_hop_limit", "_last_leap", b"_last_leap", "_lora_switch", b"_lora_switch", "_next_hop", b"_next_hop", "first_leap", b"first_leap", "hop_limit", b"hop_limit", "last_leap", b"last_leap", "lora_switch", b"lora_switch", "next_hop", b"next_hop"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_first_leap", b"_first_leap", "_hop_limit", b"_hop_limit", "_last_leap", b"_last_leap", "_lora_switch", b"_lora_switch", "_next_hop", b"_next_hop", "first_leap", b"first_leap", "hop_limit", b"hop_limit", "last_leap", b"last_leap", "lora_switch", b"lora_switch", "next_hop", b"next_hop", "num", b"num"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_first_leap", b"_first_leap"]) -> typing.Literal["first_leap"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_hop_limit", b"_hop_limit"]) -> typing.Literal["hop_limit"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_last_leap", b"_last_leap"]) -> typing.Literal["last_leap"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_lora_switch", b"_lora_switch"]) -> typing.Literal["lora_switch"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_next_hop", b"_next_hop"]) -> typing.Literal["next_hop"] | None: ...

    DEFAULT_DEST_FIELD_NUMBER: builtins.int
    NODEINFO_DEST_FIELD_NUMBER: builtins.int
    TELEMETRY_DEST_FIELD_NUMBER: builtins.int
    POSITION_DEST_FIELD_NUMBER: builtins.int
    DESTINATIONS_FIELD_NUMBER: builtins.int
    LEAPS_ENABLED_FIELD_NUMBER: builtins.int
    LEAP_CHANNEL_FIELD_NUMBER: builtins.int
    LORA_SWITCH_ENABLED_FIELD_NUMBER: builtins.int
    ONLY_LORA_SWITCH_FROM_US_FIELD_NUMBER: builtins.int
    ONLY_LEAP_SWITCH_MESSAGES_FIELD_NUMBER: builtins.int
    NODEINFO_CHANNEL_FIELD_NUMBER: builtins.int
    default_dest: builtins.int
    """
    Optional default destination for most types of packets that would otherwise be sent to broadcast.
    """
    nodeinfo_dest: builtins.int
    """
    Optional destination for nodeinfo messages. Defaults to default_dest (or if none, broadcast).
    """
    telemetry_dest: builtins.int
    """
    Optional destination for telemetry messages. Defaults to default_dest (or if none, broadcast).
    """
    position_dest: builtins.int
    """
    Optional destination for position messages. Defaults to default_dest (or if none, broadcast).
    """
    leaps_enabled: builtins.bool
    """
    Whether to use leaping or not.
    """
    leap_channel: builtins.int
    """
    Can be used to specify a dedicated channel to send leap messages on. Intended for backwards compatbility with leap-naive nodes.
    The leap channel should accordingly not use the default AQ== PSK.
    """
    lora_switch_enabled: builtins.bool
    """
    Whether to allow LoRa channel switching for destinations
    """
    only_lora_switch_from_us: builtins.bool
    """
    Whether to restrict LoRa channel switching to packets from us (not both acting as intermediate leap node and switching) 
    so that leaps can be enabled for others without also switch radio settings for others.
    """
    only_leap_switch_messages: builtins.bool
    """
    Whether to restrict leaping with LoRa radio setting changes to messages.
    Only works if only_lora_switch_from_us is not set and the message is decodable.
    """
    nodeinfo_channel: builtins.int
    """
    Option to select alternative channel to send nodeinfo broadcasts out on.
    E.g. for if your primary channel is private but you still want your info to appear on a default (but secondary) channel
    """
    @property
    def destinations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DestinationsConfig.MeshDestination]:
        """
        Configuration slots for custom handling of specified destinations
        """

    def __init__(
        self,
        *,
        default_dest: builtins.int = ...,
        nodeinfo_dest: builtins.int = ...,
        telemetry_dest: builtins.int = ...,
        position_dest: builtins.int = ...,
        destinations: collections.abc.Iterable[global___DestinationsConfig.MeshDestination] | None = ...,
        leaps_enabled: builtins.bool = ...,
        leap_channel: builtins.int = ...,
        lora_switch_enabled: builtins.bool = ...,
        only_lora_switch_from_us: builtins.bool = ...,
        only_leap_switch_messages: builtins.bool = ...,
        nodeinfo_channel: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["default_dest", b"default_dest", "destinations", b"destinations", "leap_channel", b"leap_channel", "leaps_enabled", b"leaps_enabled", "lora_switch_enabled", b"lora_switch_enabled", "nodeinfo_channel", b"nodeinfo_channel", "nodeinfo_dest", b"nodeinfo_dest", "only_leap_switch_messages", b"only_leap_switch_messages", "only_lora_switch_from_us", b"only_lora_switch_from_us", "position_dest", b"position_dest", "telemetry_dest", b"telemetry_dest"]) -> None: ...

global___DestinationsConfig = DestinationsConfig
