"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DestinationsConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MeshDestination(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NUM_FIELD_NUMBER: builtins.int
        HOP_LIMIT_FIELD_NUMBER: builtins.int
        NEXT_HOP_FIELD_NUMBER: builtins.int
        num: builtins.int
        """
        The node number for this destination
        """
        hop_limit: builtins.int
        """
        Alternative hop limit to use for this destination (zero represents default)
        """
        next_hop: builtins.int
        """
        Manual next hop specification for messages to this node (zero represents default)
        """
        def __init__(
            self,
            *,
            num: builtins.int = ...,
            hop_limit: builtins.int | None = ...,
            next_hop: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_hop_limit", b"_hop_limit", "_next_hop", b"_next_hop", "hop_limit", b"hop_limit", "next_hop", b"next_hop"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_hop_limit", b"_hop_limit", "_next_hop", b"_next_hop", "hop_limit", b"hop_limit", "next_hop", b"next_hop", "num", b"num"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_hop_limit", b"_hop_limit"]) -> typing.Literal["hop_limit"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_next_hop", b"_next_hop"]) -> typing.Literal["next_hop"] | None: ...

    DEFAULT_DEST_FIELD_NUMBER: builtins.int
    NODEINFO_DEST_FIELD_NUMBER: builtins.int
    TELEMETRY_DEST_FIELD_NUMBER: builtins.int
    POSITION_DEST_FIELD_NUMBER: builtins.int
    DESTINATIONS_FIELD_NUMBER: builtins.int
    default_dest: builtins.int
    """
    Optional default destination for most types of packets that would otherwise be sent to broadcast.
    """
    nodeinfo_dest: builtins.int
    """
    Optional destination for nodeinfo messages. Defaults to default_dest (or if none, broadcast).
    """
    telemetry_dest: builtins.int
    """
    Optional destination for telemetry messages. Defaults to default_dest (or if none, broadcast).
    """
    position_dest: builtins.int
    """
    Optional destination for position messages. Defaults to default_dest (or if none, broadcast).
    """
    @property
    def destinations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DestinationsConfig.MeshDestination]:
        """
        Configuration slots for custom handling of specified destinations
        """

    def __init__(
        self,
        *,
        default_dest: builtins.int = ...,
        nodeinfo_dest: builtins.int = ...,
        telemetry_dest: builtins.int = ...,
        position_dest: builtins.int = ...,
        destinations: collections.abc.Iterable[global___DestinationsConfig.MeshDestination] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["default_dest", b"default_dest", "destinations", b"destinations", "nodeinfo_dest", b"nodeinfo_dest", "position_dest", b"position_dest", "telemetry_dest", b"telemetry_dest"]) -> None: ...

global___DestinationsConfig = DestinationsConfig
