"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LoRaConfig(google.protobuf.message.Message):
    """
    Lora Config
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RegionCode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RegionCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LoRaConfig._RegionCode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNSET: LoRaConfig._RegionCode.ValueType  # 0
        """
        Region is not set
        """
        US: LoRaConfig._RegionCode.ValueType  # 1
        """
        United States
        """
        EU_433: LoRaConfig._RegionCode.ValueType  # 2
        """
        European Union 433mhz
        """
        EU_868: LoRaConfig._RegionCode.ValueType  # 3
        """
        European Union 868mhz
        """
        CN: LoRaConfig._RegionCode.ValueType  # 4
        """
        China
        """
        JP: LoRaConfig._RegionCode.ValueType  # 5
        """
        Japan
        """
        ANZ: LoRaConfig._RegionCode.ValueType  # 6
        """
        Australia / New Zealand
        """
        KR: LoRaConfig._RegionCode.ValueType  # 7
        """
        Korea
        """
        TW: LoRaConfig._RegionCode.ValueType  # 8
        """
        Taiwan
        """
        RU: LoRaConfig._RegionCode.ValueType  # 9
        """
        Russia
        """
        IN: LoRaConfig._RegionCode.ValueType  # 10
        """
        India
        """
        NZ_865: LoRaConfig._RegionCode.ValueType  # 11
        """
        New Zealand 865mhz
        """
        TH: LoRaConfig._RegionCode.ValueType  # 12
        """
        Thailand
        """
        LORA_24: LoRaConfig._RegionCode.ValueType  # 13
        """
        WLAN Band
        """
        UA_433: LoRaConfig._RegionCode.ValueType  # 14
        """
        Ukraine 433mhz
        """
        UA_868: LoRaConfig._RegionCode.ValueType  # 15
        """
        Ukraine 868mhz
        """
        MY_433: LoRaConfig._RegionCode.ValueType  # 16
        """
        Malaysia 433mhz
        """
        MY_919: LoRaConfig._RegionCode.ValueType  # 17
        """
        Malaysia 919mhz
        """
        SG_923: LoRaConfig._RegionCode.ValueType  # 18
        """
        Singapore 923mhz
        """
        PH_433: LoRaConfig._RegionCode.ValueType  # 19
        """
        Philippines 433mhz
        """
        PH_868: LoRaConfig._RegionCode.ValueType  # 20
        """
        Philippines 868mhz
        """
        PH_915: LoRaConfig._RegionCode.ValueType  # 21
        """
        Philippines 915mhz
        """

    class RegionCode(_RegionCode, metaclass=_RegionCodeEnumTypeWrapper): ...
    UNSET: LoRaConfig.RegionCode.ValueType  # 0
    """
    Region is not set
    """
    US: LoRaConfig.RegionCode.ValueType  # 1
    """
    United States
    """
    EU_433: LoRaConfig.RegionCode.ValueType  # 2
    """
    European Union 433mhz
    """
    EU_868: LoRaConfig.RegionCode.ValueType  # 3
    """
    European Union 868mhz
    """
    CN: LoRaConfig.RegionCode.ValueType  # 4
    """
    China
    """
    JP: LoRaConfig.RegionCode.ValueType  # 5
    """
    Japan
    """
    ANZ: LoRaConfig.RegionCode.ValueType  # 6
    """
    Australia / New Zealand
    """
    KR: LoRaConfig.RegionCode.ValueType  # 7
    """
    Korea
    """
    TW: LoRaConfig.RegionCode.ValueType  # 8
    """
    Taiwan
    """
    RU: LoRaConfig.RegionCode.ValueType  # 9
    """
    Russia
    """
    IN: LoRaConfig.RegionCode.ValueType  # 10
    """
    India
    """
    NZ_865: LoRaConfig.RegionCode.ValueType  # 11
    """
    New Zealand 865mhz
    """
    TH: LoRaConfig.RegionCode.ValueType  # 12
    """
    Thailand
    """
    LORA_24: LoRaConfig.RegionCode.ValueType  # 13
    """
    WLAN Band
    """
    UA_433: LoRaConfig.RegionCode.ValueType  # 14
    """
    Ukraine 433mhz
    """
    UA_868: LoRaConfig.RegionCode.ValueType  # 15
    """
    Ukraine 868mhz
    """
    MY_433: LoRaConfig.RegionCode.ValueType  # 16
    """
    Malaysia 433mhz
    """
    MY_919: LoRaConfig.RegionCode.ValueType  # 17
    """
    Malaysia 919mhz
    """
    SG_923: LoRaConfig.RegionCode.ValueType  # 18
    """
    Singapore 923mhz
    """
    PH_433: LoRaConfig.RegionCode.ValueType  # 19
    """
    Philippines 433mhz
    """
    PH_868: LoRaConfig.RegionCode.ValueType  # 20
    """
    Philippines 868mhz
    """
    PH_915: LoRaConfig.RegionCode.ValueType  # 21
    """
    Philippines 915mhz
    """

    class _ModemPreset:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ModemPresetEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LoRaConfig._ModemPreset.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LONG_FAST: LoRaConfig._ModemPreset.ValueType  # 0
        """
        Long Range - Fast
        """
        LONG_SLOW: LoRaConfig._ModemPreset.ValueType  # 1
        """
        Long Range - Slow
        """
        VERY_LONG_SLOW: LoRaConfig._ModemPreset.ValueType  # 2
        """
        Very Long Range - Slow
        Deprecated in 2.5: Works only with txco and is unusably slow
        """
        MEDIUM_SLOW: LoRaConfig._ModemPreset.ValueType  # 3
        """
        Medium Range - Slow
        """
        MEDIUM_FAST: LoRaConfig._ModemPreset.ValueType  # 4
        """
        Medium Range - Fast
        """
        SHORT_SLOW: LoRaConfig._ModemPreset.ValueType  # 5
        """
        Short Range - Slow
        """
        SHORT_FAST: LoRaConfig._ModemPreset.ValueType  # 6
        """
        Short Range - Fast
        """
        LONG_MODERATE: LoRaConfig._ModemPreset.ValueType  # 7
        """
        Long Range - Moderately Fast
        """
        SHORT_TURBO: LoRaConfig._ModemPreset.ValueType  # 8
        """
        Short Range - Turbo
        This is the fastest preset and the only one with 500kHz bandwidth.
        It is not legal to use in all regions due to this wider bandwidth.
        """
        NO_PRESET: LoRaConfig._ModemPreset.ValueType  # 255
        """
        Used in LoRaConfigLite to signify modem settings that don't use a preset
        """

    class ModemPreset(_ModemPreset, metaclass=_ModemPresetEnumTypeWrapper):
        """
        Standard predefined channel settings
        Note: these mappings must match ModemPreset Choice in the device code.
        """

    LONG_FAST: LoRaConfig.ModemPreset.ValueType  # 0
    """
    Long Range - Fast
    """
    LONG_SLOW: LoRaConfig.ModemPreset.ValueType  # 1
    """
    Long Range - Slow
    """
    VERY_LONG_SLOW: LoRaConfig.ModemPreset.ValueType  # 2
    """
    Very Long Range - Slow
    Deprecated in 2.5: Works only with txco and is unusably slow
    """
    MEDIUM_SLOW: LoRaConfig.ModemPreset.ValueType  # 3
    """
    Medium Range - Slow
    """
    MEDIUM_FAST: LoRaConfig.ModemPreset.ValueType  # 4
    """
    Medium Range - Fast
    """
    SHORT_SLOW: LoRaConfig.ModemPreset.ValueType  # 5
    """
    Short Range - Slow
    """
    SHORT_FAST: LoRaConfig.ModemPreset.ValueType  # 6
    """
    Short Range - Fast
    """
    LONG_MODERATE: LoRaConfig.ModemPreset.ValueType  # 7
    """
    Long Range - Moderately Fast
    """
    SHORT_TURBO: LoRaConfig.ModemPreset.ValueType  # 8
    """
    Short Range - Turbo
    This is the fastest preset and the only one with 500kHz bandwidth.
    It is not legal to use in all regions due to this wider bandwidth.
    """
    NO_PRESET: LoRaConfig.ModemPreset.ValueType  # 255
    """
    Used in LoRaConfigLite to signify modem settings that don't use a preset
    """

    USE_PRESET_FIELD_NUMBER: builtins.int
    MODEM_PRESET_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    SPREAD_FACTOR_FIELD_NUMBER: builtins.int
    CODING_RATE_FIELD_NUMBER: builtins.int
    FREQUENCY_OFFSET_FIELD_NUMBER: builtins.int
    REGION_FIELD_NUMBER: builtins.int
    HOP_LIMIT_FIELD_NUMBER: builtins.int
    TX_ENABLED_FIELD_NUMBER: builtins.int
    TX_POWER_FIELD_NUMBER: builtins.int
    CHANNEL_NUM_FIELD_NUMBER: builtins.int
    OVERRIDE_DUTY_CYCLE_FIELD_NUMBER: builtins.int
    SX126X_RX_BOOSTED_GAIN_FIELD_NUMBER: builtins.int
    OVERRIDE_FREQUENCY_FIELD_NUMBER: builtins.int
    PA_FAN_DISABLED_FIELD_NUMBER: builtins.int
    IGNORE_INCOMING_FIELD_NUMBER: builtins.int
    IGNORE_MQTT_FIELD_NUMBER: builtins.int
    CONFIG_OK_TO_MQTT_FIELD_NUMBER: builtins.int
    use_preset: builtins.bool
    """
    When enabled, the `modem_preset` fields will be adhered to, else the `bandwidth`/`spread_factor`/`coding_rate`
    will be taked from their respective manually defined fields
    """
    modem_preset: global___LoRaConfig.ModemPreset.ValueType
    """
    Either modem_config or bandwidth/spreading/coding will be specified - NOT BOTH.
    As a heuristic: If bandwidth is specified, do not use modem_config.
    Because protobufs take ZERO space when the value is zero this works out nicely.
    This value is replaced by bandwidth/spread_factor/coding_rate.
    If you'd like to experiment with other options add them to MeshRadio.cpp in the device code.
    """
    bandwidth: builtins.int
    """
    Bandwidth in MHz
    Certain bandwidth numbers are 'special' and will be converted to the
    appropriate floating point value: 31 -> 31.25MHz
    """
    spread_factor: builtins.int
    """
    A number from 7 to 12.
    Indicates number of chirps per symbol as 1<<spread_factor.
    """
    coding_rate: builtins.int
    """
    The denominator of the coding rate.
    ie for 4/5, the value is 5. 4/8 the value is 8.
    """
    frequency_offset: builtins.float
    """
    This parameter is for advanced users with advanced test equipment, we do not recommend most users use it.
    A frequency offset that is added to to the calculated band center frequency.
    Used to correct for crystal calibration errors.
    """
    region: global___LoRaConfig.RegionCode.ValueType
    """
    The region code for the radio (US, CN, EU433, etc...)
    """
    hop_limit: builtins.int
    """
    Maximum number of hops. This can't be greater than 7.
    Default of 3
    Attempting to set a value > 7 results in the default
    """
    tx_enabled: builtins.bool
    """
    Disable TX from the LoRa radio. Useful for hot-swapping antennas and other tests.
    Defaults to false
    """
    tx_power: builtins.int
    """
    If zero, then use default max legal continuous power (ie. something that won't
    burn out the radio hardware)
    In most cases you should use zero here.
    Units are in dBm.
    """
    channel_num: builtins.int
    """
    This controls the actual hardware frequency the radio transmits on.
    Most users should never need to be exposed to this field/concept.
    A channel number between 1 and NUM_CHANNELS (whatever the max is in the current region).
    If ZERO then the rule is "use the old channel name hash based
    algorithm to derive the channel number")
    If using the hash algorithm the channel number will be: hash(channel_name) %
    NUM_CHANNELS (Where num channels depends on the regulatory region).

    65535 is treated as "unset" for some purposes
    """
    override_duty_cycle: builtins.bool
    """
    If true, duty cycle limits will be exceeded and thus you're possibly not following
    the local regulations if you're not a HAM.
    Has no effect if the duty cycle of the used region is 100%.
    """
    sx126x_rx_boosted_gain: builtins.bool
    """
    If true, sets RX boosted gain mode on SX126X based radios
    """
    override_frequency: builtins.float
    """
    This parameter is for advanced users and licensed HAM radio operators.
    Ignore Channel Calculation and use this frequency instead. The frequency_offset
    will still be applied. This will allow you to use out-of-band frequencies.
    Please respect your local laws and regulations. If you are a HAM, make sure you
    enable HAM mode and turn off encryption.
    """
    pa_fan_disabled: builtins.bool
    """
    If true, disable the build-in PA FAN using pin define in RF95_FAN_EN.
    """
    ignore_mqtt: builtins.bool
    """
    If true, the device will not process any packets received via LoRa that passed via MQTT anywhere on the path towards it.
    """
    config_ok_to_mqtt: builtins.bool
    """
    Sets the ok_to_mqtt bit on outgoing packets
    """
    @property
    def ignore_incoming(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """
        For testing it is useful sometimes to force a node to never listen to
        particular other nodes (simulating radio out of range). All nodenums listed
        in ignore_incoming will have packets they send dropped on receive (by router.cpp)
        """

    def __init__(
        self,
        *,
        use_preset: builtins.bool = ...,
        modem_preset: global___LoRaConfig.ModemPreset.ValueType = ...,
        bandwidth: builtins.int = ...,
        spread_factor: builtins.int = ...,
        coding_rate: builtins.int = ...,
        frequency_offset: builtins.float = ...,
        region: global___LoRaConfig.RegionCode.ValueType = ...,
        hop_limit: builtins.int = ...,
        tx_enabled: builtins.bool = ...,
        tx_power: builtins.int = ...,
        channel_num: builtins.int = ...,
        override_duty_cycle: builtins.bool = ...,
        sx126x_rx_boosted_gain: builtins.bool = ...,
        override_frequency: builtins.float = ...,
        pa_fan_disabled: builtins.bool = ...,
        ignore_incoming: collections.abc.Iterable[builtins.int] | None = ...,
        ignore_mqtt: builtins.bool = ...,
        config_ok_to_mqtt: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bandwidth", b"bandwidth", "channel_num", b"channel_num", "coding_rate", b"coding_rate", "config_ok_to_mqtt", b"config_ok_to_mqtt", "frequency_offset", b"frequency_offset", "hop_limit", b"hop_limit", "ignore_incoming", b"ignore_incoming", "ignore_mqtt", b"ignore_mqtt", "modem_preset", b"modem_preset", "override_duty_cycle", b"override_duty_cycle", "override_frequency", b"override_frequency", "pa_fan_disabled", b"pa_fan_disabled", "region", b"region", "spread_factor", b"spread_factor", "sx126x_rx_boosted_gain", b"sx126x_rx_boosted_gain", "tx_enabled", b"tx_enabled", "tx_power", b"tx_power", "use_preset", b"use_preset"]) -> None: ...

global___LoRaConfig = LoRaConfig

@typing.final
class LoRaConfigLite(google.protobuf.message.Message):
    """
    Simplified Lora Config for switching between presets
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODEM_PRESET_FIELD_NUMBER: builtins.int
    CHANNEL_NUM_FIELD_NUMBER: builtins.int
    modem_preset: global___LoRaConfig.ModemPreset.ValueType
    """
    Modem preset to select
    """
    channel_num: builtins.int
    """
    LoRa frequency channel slot to use.
    65535 is treated as "unset" for some purposes.
    """
    def __init__(
        self,
        *,
        modem_preset: global___LoRaConfig.ModemPreset.ValueType = ...,
        channel_num: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_num", b"channel_num", "modem_preset", b"modem_preset"]) -> None: ...

global___LoRaConfigLite = LoRaConfigLite
